# Generated by Django 2.1.9 on 2019-06-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio_app', '0001_initial'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_cms_integration_blogpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.Blog')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
